### ISSUE TITLE
AssertionError: model parallel group is not initialized

### ISSUE THREAD

**Issue by nikich340** [sberbank-ai/ru-gpts#104]
```
Traceback (most recent call last):
  File "D:\_ruGPT3\ru-gpts\run_gpt3medium.py", line 11, in <module>
    gpt = RuGPT3XL.from_pretrained("sber-gpt3-medium", seq_len=512)
  File "D:\_ruGPT3\ru-gpts\src\xl_wrapper.py", line 178, in from_pretrained
    mpu.model_parallel_cuda_manual_seed(seed)
  File "D:\_ruGPT3\ru-gpts\src\mpu\random.py", line 217, in model_parallel_cuda_manual_seed
    model_parallel_seed = offset + get_model_parallel_rank()
  File "D:\_ruGPT3\ru-gpts\src\mpu\initialize.py", line 109, in get_model_parallel_rank
    return torch.distributed.get_rank(group=get_model_parallel_group())
  File "D:\_ruGPT3\ru-gpts\src\mpu\initialize.py", line 90, in get_model_parallel_group
    assert _MODEL_PARALLEL_GROUP is not None, \
AssertionError: model parallel group is not initialized
```

Used "Usage" example code but with rugpt3-medium model. Os: windows 10, py 3.9, gpu: rtx 3060 laptop.

**Comment by LEv145** [comment]
I have same problem with `RuGPT3XL`
```py
>>> gpt = RuGPT3XL.from_pretrained("sberbank-ai/rugpt3xl", seq_len=512)
The default process group has already initialized...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/ru-gpts/src/xl_wrapper.py", line 178, in from_pretrained
    mpu.model_parallel_cuda_manual_seed(seed)
  File "/opt/ru-gpts/src/mpu/random.py", line 217, in model_parallel_cuda_manual_seed
    model_parallel_seed = offset + get_model_parallel_rank()
  File "/opt/ru-gpts/src/mpu/initialize.py", line 109, in get_model_parallel_rank
    return torch.distributed.get_rank(group=get_model_parallel_group())
  File "/opt/ru-gpts/src/mpu/initialize.py", line 90, in get_model_parallel_group
    assert _MODEL_PARALLEL_GROUP is not None, \
AssertionError: model parallel group is not initialized
```

**Comment by LEv145** [comment]
Maybe problem with cpu
https://github.com/ai-forever/ru-gpts/blob/master/examples/ruGPT3XL_generation.ipynb
![изображение](https://user-images.githubusercontent.com/40071054/218875610-117bb769-ddb8-4b1b-96d9-f70731ef2ba1.png)
