### ISSUE TITLE
eos_token_id is None

### ISSUE THREAD

**Issue by mikhovr** [sberbank-ai/ru-gpts#28]
The tokenizer has a special token `eos_token = '<|endoftext|>'`. However, this token seems to be missing in vocabulary.
Hence, when I try to encode a sequence like so:

`tokenizer.encode("привет" + tokenizer.eos_token")`, I get `[960, 577, None]` which follows to 

```
Traceback (most recent call last):
  File "/home/superuser/khovrichev/gpt2bot/run_console_bot.py", line 14, in <module>
    run_bot(**config)
  File "/home/superuser/khovrichev/gpt2bot/gpt2bot/console_bot.py", line 66, in run_bot
    bot_messages = generate_text(prompt, pipeline, **generator_kwargs)
  File "/home/superuser/khovrichev/gpt2bot/gpt2bot/utils.py", line 301, in generate_text
    responses = generator.generate_next(prompt)
  File "/home/superuser/khovrichev/gpt2bot/gpt2bot/utils.py", line 103, in generate_next
    encoded_prompt = self.tokenizer.encode(prompt_text, add_special_tokens=False, return_tensors="pt")
  File "/home/superuser/khovrichev/ru-gpts/gpt_env/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 919, in encode
    **kwargs,
  File "/home/superuser/khovrichev/ru-gpts/gpt_env/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 1069, in encode_plus
    return_special_tokens_mask=return_special_tokens_mask,
  File "/home/superuser/khovrichev/ru-gpts/gpt_env/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 1463, in prepare_for_model
    encoded_inputs["input_ids"] = torch.tensor([encoded_inputs["input_ids"]])
RuntimeError: Could not infer dtype of NoneType
```

Why eos_token is present in the tokenizer but is absent in vocab?

**Comment by king-menin** [comment]
We train this without this token. But first tokens are specials in vocab. And what version of transformers do you use?

**Comment by mikhovr** [comment]
To reproduce this behaviour, I use `transformers==2.8.0` (from requirements.txt). My global goal is to make the model generate sentences separated from context, not just continue text.

**Comment by king-menin** [comment]
Model was trained without this token you should add eos token and finetune model. Also we release models trained with eos token.

**Comment by mikhovr** [comment]
Thank you! I'll add eos token manually.
