### ISSUE TITLE
colab RuGPT3FinetuneHF.ipynb is not working

### ISSUE THREAD

**Issue by sc0eur** [sberbank-ai/ru-gpts#43]
Перестал работать ноутбук для файнтюнинга на колабе: https://colab.research.google.com/github/sberbank-ai/ru-gpts/blob/master/examples/Finetune_RuGPTs_with_HF.ipynb  
При выполнении ячейки `Train` ошибка:  
```
2021-03-09 17:40:36.000492: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
Traceback (most recent call last):
  File "ru-gpts/pretrain_transformers.py", line 33, in <module>
    from transformers import (
  File "/usr/local/lib/python3.7/dist-packages/transformers/__init__.py", line 626, in <module>
    from .trainer import Trainer
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer.py", line 69, in <module>
    from .trainer_pt_utils import (
  File "/usr/local/lib/python3.7/dist-packages/transformers/trainer_pt_utils.py", line 40, in <module>
    from torch.optim.lr_scheduler import SAVE_STATE_WARNING
ImportError: cannot import name 'SAVE_STATE_WARNING' from 'torch.optim.lr_scheduler' (/usr/local/lib/python3.7/dist-packages/torch/optim/lr_scheduler.py)
```

**Comment by king-menin** [comment]
Версия трансформеров не та скорее всего. Попробуйте с 3.5.1

**Comment by 1LISA2** [comment]
![images](https://user-images.githubusercontent.com/103248540/188132427-32968d32-1a31-4d90-8d1c-945c5e3b3a16.jpeg)

**Comment by 1LISA2** [comment]
what up ?
