### ISSUE TITLE
Не собирается apex 

### ISSUE THREAD

**Issue by denismashukov** [sberbank-ai/ru-gpts#76]
Finetune_and_generate_RuGPTs_deepspeed_megatron.ipynb

После каких-то обновлений не собирается apex 
полный лог https://justpaste.it/361ue

```

/usr/local/lib/python3.7/dist-packages/torch/include/ATen/core/op_registration/op_whitelist.h(39): warning: integer conversion resulted in a change of sign

    csrc/fused_dense_cuda.cu(415): error: identifier "CUBLASLT_EPILOGUE_GELU_AUX" is undefined

    csrc/fused_dense_cuda.cu(427): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_POINTER" is undefined

    csrc/fused_dense_cuda.cu(428): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_LD" is undefined

    csrc/fused_dense_cuda.cu(435): error: identifier "CUBLASLT_EPILOGUE_GELU_AUX_BIAS" is undefined

    csrc/fused_dense_cuda.cu(555): error: identifier "CUBLASLT_EPILOGUE_GELU_AUX" is undefined

    csrc/fused_dense_cuda.cu(567): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_POINTER" is undefined

    csrc/fused_dense_cuda.cu(568): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_LD" is undefined

    csrc/fused_dense_cuda.cu(575): error: identifier "CUBLASLT_EPILOGUE_GELU_AUX_BIAS" is undefined

    csrc/fused_dense_cuda.cu(687): error: identifier "CUBLASLT_EPILOGUE_BGRADB" is undefined

    csrc/fused_dense_cuda.cu(826): error: identifier "CUBLASLT_EPILOGUE_BGRADB" is undefined

    csrc/fused_dense_cuda.cu(920): error: identifier "CUBLASLT_EPILOGUE_DGELU_BGRAD" is undefined

    csrc/fused_dense_cuda.cu(936): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_POINTER" is undefined

    csrc/fused_dense_cuda.cu(940): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_LD" is undefined

    csrc/fused_dense_cuda.cu(1055): error: identifier "CUBLASLT_EPILOGUE_DGELU_BGRAD" is undefined

    csrc/fused_dense_cuda.cu(1071): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_POINTER" is undefined

    csrc/fused_dense_cuda.cu(1075): error: identifier "CUBLASLT_MATMUL_DESC_EPILOGUE_AUX_LD" is undefined

    csrc/fused_dense_cuda.cu(1203): warning: variable "beta_one" was declared but never referenced

    csrc/fused_dense_cuda.cu(1332): warning: variable "beta_one" was declared but never referenced

    16 errors detected in the compilation of "csrc/fused_dense_cuda.cu".
    error: command '/usr/local/cuda/bin/nvcc' failed with exit status 1
    Running setup.py install for apex ... error
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rpvxsyuz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rpvxsyuz/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-78od8nzj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/apex Check the logs for full command output.
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/req_install.py", line 825, in install
    req_description=str(self.req),
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/install/legacy.py", line 81, in install
    raise LegacyInstallFailure
pip._internal.operations.install.legacy.LegacyInstallFailure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/base_command.py", line 180, in _main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/cli/req_command.py", line 199, in wrapper
    return func(self, options, args)
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/commands/install.py", line 402, in run
    pycompile=options.compile,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/__init__.py", line 85, in install_given_reqs
    pycompile=pycompile,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/req/req_install.py", line 829, in install
    six.reraise(*exc.parent)
  File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/operations/install/legacy.py", line 71, in install
    cwd=unpacked_source_directory,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 278, in runner
    spinner=spinner,
  File "/usr/local/lib/python3.7/dist-packages/pip/_internal/utils/subprocess.py", line 244, in call_subprocess
    raise InstallationSubprocessError(proc.returncode, command_desc)
pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-rpvxsyuz/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-rpvxsyuz/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' --cpp_ext --cuda_ext install --record /tmp/pip-record-78od8nzj/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.7/apex Check the logs for full command output.
Removed build tracker: '/tmp/pip-req-tracker-wu3gcwg7'
```

**Comment by sergeykorneev1996** [comment]
Столкнулся недавно с той же проблемой
